README.md, jdkhttp/pom.xml, springboot/pom.xml, thorntail/pom.xml
Added kjar dep in the webapps @mariofusco @danielezonca
=> Added kjar dep in the webapps

hacep/src/main/java/org/kie/hacep/consumer/FactHandlesManager.java
@mariofusco please review. Needs to be merged along with https://github.com/kiegroup/drools/pull/2468.
=> DROOLS-4343 Change FactHandle ID from int to long

jdkhttp/pom.xml, pom.xml, springboot/kubernetes/debug_pod.yaml, springboot/kubernetes/deployment_registry.yaml, springboot/pom.xml, thorntail/pom.xml
fix for Fabric8 k8s client dependencies broken using the supported dependencies in the project
@mariofusco @jiripetrlik
=> [Drools-4384] fix for Fabric8 k8s client 

integration/src/test/java/org/kie/hacep/KafkaFullTopicsTests.java, integration/src/test/java/org/kie/hacep/KafkaUtilTest.java, integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java, integration/src/test/java/org/kie/hacep/PodAsLeaderTest.java, integration/src/test/java/org/kie/hacep/PodAsReplicaTest.java, integration/src/test/java/org/kie/hacep/RemoteKieSessionImplTest.java, integration/src/test/java/org/kie/hacep/RemoteStreamingKieSessionImplTest.java, integration/src/test/java/org/kie/hacep/SnapshotOnDemandTest.java
@jiripetrlik @mariofusco @danielezonca
=> [Drools 4398] Timeout to avoid freezing test

integration/src/test/java/org/kie/hacep/KafkaFullTopicsTests.java, integration/src/test/java/org/kie/hacep/KafkaTest.java, integration/src/test/java/org/kie/hacep/KafkaUtilTest.java, integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java, integration/src/test/java/org/kie/hacep/PodAsLeaderTest.java, integration/src/test/java/org/kie/hacep/PodAsReplicaTest.java, integration/src/test/java/org/kie/hacep/PrinterKafkaImpl.java, integration/src/test/java/org/kie/hacep/SnapshotOnDemandTest.java, integration/src/test/resources/logback-test.xml
Changed test topic name from logs (name used by kafka) to testlogs  @danielezonca @jiripetrlik @mariofusco
=> changed test topic's name

thorntail/README.md, thorntail/kubernetes/deployment.yaml, thorntail/pom.xml, thorntail/src/main/java/org/kie/hacep/endpoint/Env.java, thorntail/src/main/java/org/kie/hacep/endpoint/Liveness.java, thorntail/src/main/java/org/kie/hacep/endpoint/NotFoundExceptionMapper.java, thorntail/src/main/java/org/kie/hacep/endpoint/Readiness.java, thorntail/src/main/java/org/kie/hacep/endpoint/RestApplication.java
=> [DROOLS-4489] Fix Thorntail rest

hacep/src/main/java/org/kie/hacep/core/infra/consumer/DefaultKafkaConsumer.java
@mariofusco @jiripetrlik @danielezonca
=> [DROOLS-4371] fix findbugs alarms

kie-remote/src/main/java/org/kie/remote/impl/consumer/ListenerThread.java, sample-hacep-project/sample-hacep-project-client/src/main/java/org/kie/hacep/sample/client/ClientProducerDemo.java
@danielezonca  @jiripetrlik @mariofusco
=>  [Drools 4500] Fix  ClientProducerDemo misconfiguration

kie-remote/src/main/java/org/kie/remote/impl/consumer/ListenerThread.java, sample-hacep-project/sample-hacep-project-client/src/main/java/org/kie/hacep/sample/client/ClientProducerDemo.java
=> 7.26.x [[Drools 4500] Fix ClientProducerDemo misconfiguration ]

jdkhttp/Dockerfile, springboot/Dockerfile, thorntail/Dockerfile
@jiripetrlik @danielezonca @mariofusco @mareknovotny 
version with jdk
=> [DROOLS-4505]Replaced Alpine with UBI

hacep/src/main/java/org/kie/hacep/core/infra/consumer/DefaultKafkaConsumer.java
@mariofusco @jiripetrlik @danielezonca
=> [Drools-4514] Number of facts in KIE session does not match after leader fails

kie-remote/src/main/java/org/kie/remote/RemoteStreamingKieSession.java
@danielezonca @mariofusco @jiripetrlik
=> [Drools 4538] Added missing license header

kie-remote/src/main/java/org/kie/remote/RemoteStreamingKieSession.java
@danielezonca @mariofusco @jiripetrlik @mareknovotny
=> [Drools-4538] Missing license header

pom.xml, thorntail/pom.xml
https://issues.jboss.org/browse/RHDM-1093
=> RHDM-1093 fixing inconsistences between kie-parent

hacep/pom.xml, pom.xml, springboot/pom.xml, thorntail/pom.xml
Replaced javax deps with org.jboss.spec.javax
@mareknovotny @jiripetrlik @danielezonca @mariofusco
=> [Drools-4550] Fixing inconsistencies between kie parent 

pom.xml, thorntail/pom.xml
https://issues.jboss.org/browse/RHDM-1093
backporting of #43
=> [7.26.x] - RHDM-1093 

hacep/pom.xml, pom.xml, springboot/pom.xml, thorntail/pom.xml
=> [Drools-4550] Fixing inconsistencies between kie parent

hacep/src/main/java/org/kie/hacep/consumer/DroolsConsumerHandler.java, hacep/src/main/java/org/kie/hacep/core/infra/consumer/DefaultKafkaConsumer.java, integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java
=> [Drools-4628] Fix PodAsALeaderSnapshotTest random failure

jdkhttp/README.md, springboot/README.md
=> [Drools-4653] Document build with local registry on Openshift 4.x

hacep/src/main/java/org/kie/hacep/Config.java, hacep/src/main/java/org/kie/hacep/EnvConfig.java, hacep/src/main/java/org/kie/hacep/PollUnit.java, hacep/src/main/java/org/kie/hacep/core/infra/DefaultSessionSnapShooter.java, hacep/src/main/java/org/kie/hacep/core/infra/consumer/ConsumerController.java, hacep/src/main/java/org/kie/hacep/core/infra/consumer/ConsumerThread.java, hacep/src/main/java/org/kie/hacep/core/infra/consumer/DefaultKafkaConsumer.java, hacep/src/main/java/org/kie/hacep/core/infra/consumer/LocalConsumer.java, hacep/src/main/java/org/kie/hacep/core/infra/utils/ConsumerUtils.java, hacep/src/main/java/org/kie/hacep/core/infra/utils/SnapshotOnDemandUtils.java, integration/src/test/java/org/kie/hacep/KafkaUtilTest.java, integration/src/test/java/org/kie/hacep/PodAsReplicaTest.java, integration/src/test/java/org/kie/hacep/SnapshotOnDemandTest.java
Configurable poll time for consumers events,control,kiesessioninfo and separately for snapshot
@danielezonca  @jiripetrlik
=> [drools-4643]Configurable consumers

sample-hacep-project/sample-hacep-project-client/src/main/java/org/kie/hacep/sample/client/ClientProducerDemo.java, sample-hacep-project/sample-hacep-project-client/src/main/resources/configuration.properties
externalize the client properties in order to simplify the configuration
=> external props

hacep/src/main/java/org/kie/hacep/core/infra/DefaultSessionSnapShooter.java, hacep/src/main/java/org/kie/hacep/core/infra/utils/SnapshotOnDemandUtils.java
=> [Drools-4802]fix topic partition check

integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java
Increased attempt number during tests
@jiripetrlik @danielezonca
=> [drools-4926] attempt number

integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java, jdkhttp/pom.xml, pom.xml, springboot/pom.xml
Fix CVE-2019-10219
@mareknovotny 
@jiripetrlik 
@mariofusco 
@danielezonca 
related to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1157
=>  [Drools-4915] fix for CVE-2019-10219

integration/src/test/java/org/kie/hacep/PodAsLeaderSnapshotTest.java, pom.xml, springboot/pom.xml
Aligned to springboot 2.2.2.RELEASE and spring 5.2.2.RELEASE used in the kie parent
@jiripetrlik 
@danielezonca 
@mariofusco
=> [Drools-4918] Aligned springboot and springframework to the kieparent

docs/installation-openshift-3.11/jdkhttp/README.md, docs/installation-openshift-3.11/springboot/README.md, docs/installation-openshift-4.x/jdkhttp/README.md, docs/installation-openshift-4.x/springboot/README.md, docs/kjar/README.md
@jiripetrlik @danielezonca @mariofusco
=> [Drools 4951] Update docs to explain security constraints

sample-hacep-project/sample-hacep-project-kjar/pom.xml
https://github.com/kiegroup/droolsjbpm-integration/pull/1864
https://github.com/kiegroup/drools/pull/2636
https://github.com/kiegroup/openshift-drools-hacep/pull/68
https://github.com/kiegroup/kie-wb-playground/pull/78
https://github.com/kiegroup/droolsjbpm-knowledge/pull/397
=> [DROOLS-4092] Default to executable model in the kie-maven-plugin

docs/installation-openshift-3.11/jdkhttp/README.md, docs/installation-openshift-3.11/springboot/README.md, docs/installation-openshift-4.x/jdkhttp/README.md, docs/installation-openshift-4.x/springboot/README.md
@jiripetrlik @danielezonca aligned docs to https://github.com/kiegroup/openshift-drools-hacep/pull/80
=> [Drools-5165] Removed security context from docs

docs/installation-openshift-3.11/jdkhttp/README.md, docs/installation-openshift-3.11/springboot/README.md, docs/installation-openshift-4.x/jdkhttp/README.md, docs/installation-openshift-4.x/springboot/README.md, jdkhttp/src/main/resources/logback.xml, springboot/src/main/resources/logback.xml
Log level can be configured using environment variables. This will simplify debugging and finding possible problems.
=> [DROOLS-5175] Log levels can be configured using environment variables

ha-core-infra/pom.xml, hacep/pom.xml, jdkhttp/pom.xml, pom.xml, springboot/pom.xml
https://issues.redhat.com/browse/RHPAM-2800
for XSD validation
=> RHPAM-2800: fixing declaration of pom.xml to be valid

hacep/pom.xml, integration/pom.xml, jdkhttp/pom.xml, pom.xml, springboot/pom.xml
for XSD validation
backport of #85
=> [7.33.x] RHPAM-2800: fixing declaration of pom.xml to be valid

.gitignore, pom.xml, springboot/pom.xml
**JIRA**: 
[JBPM-9659](https://issues.redhat.com/browse/JBPM-9659)
**Related PRs*: 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1693
https://github.com/kiegroup/kie-soup/pull/216
https://github.com/kiegroup/droolsjbpm-knowledge/pull/543
https://github.com/kiegroup/drools/pull/3757
https://github.com/kiegroup/optaplanner/pull/1463
https://github.com/kiegroup/lienzo-tests/pull/124
https://github.com/kiegroup/appformer/pull/1163
https://github.com/kiegroup/kie-uberfire-extensions/pull/122
https://github.com/kiegroup/jbpm/pull/1974
https://github.com/kiegroup/kie-jpmml-integration/pull/62
https://github.com/kiegroup/droolsjbpm-integration/pull/2539
https://github.com/kiegroup/kie-wb-playground/pull/115
https://github.com/kiegroup/kie-wb-common/pull/3660 …
=> JBPM-9659: Upgrade deployments to WildFly 23
